const assert = require('assert');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { photos } = require('../miniprogram/utils/contributedPhotos');
const { photoCollections } = require('../miniprogram/utils/photoCollections');
const { photoGallery, redVillages } = require('../miniprogram/utils/data');
const records = require('../参赛材料/用户补充照片记录.json');
assert.strictEqual(photos.length, 13);
assert.strictEqual(new Set(photos.map(p => p.id)).size, 13);
assert.strictEqual(photoGallery.filter(p => p.collectionPhotoId).length, 13);
for (const photo of photos) {
  const entry = photoGallery.find(p => p.collectionPhotoId === photo.id);
  assert(entry.available && entry.src === photo.thumbnailSrc);
  const record = records.find(p => p.id === photo.id);
  for (const [file, hash] of [[record.outputPath, record.sha256], [record.thumbnailPath, record.thumbnailSha256]]) {
    const bytes = fs.readFileSync(path.join(__dirname, '..', file));
    assert.strictEqual(crypto.createHash('sha256').update(bytes).digest('hex'), hash);
    assert(bytes.length < 200 * 1024);
  }
}
for (const group of photoCollections) assert.strictEqual(photos.filter(p => p.group === group.id).length, group.count);
assert(photos.filter(p => p.group === 'reference').every(p => !p.siteId));
assert(!redVillages.flatMap(v => v.sites || []).find(s => s.id === 'site_5').latitude, 'photographs must not invent coordinates');
let definition;
global.Page = page => { definition = page; };
let navigated, preview;
global.wx = { navigateTo: options => { navigated = options.url; }, previewImage: options => { preview = options; }, showToast() {} };
const instantiate = () => ({ ...definition, data: JSON.parse(JSON.stringify(definition.data)), setData(data) { Object.assign(this.data, data); } });
require('../miniprogram/assets/gallery/index');
const gallery = instantiate();
gallery.data.allPhotos = photoGallery;
gallery.filterPhotos('contributed');
assert.strictEqual(gallery.data.photos.length, 13);
gallery.onPhotoTap({ currentTarget: { dataset: { index: 0 } } });
assert(navigated.startsWith('/contributions/gallery/index?group='));
gallery.filterPhotos('all');
gallery.onPhotoTap({ currentTarget: { dataset: { index: gallery.data.photos.findIndex(p => !p.collectionPhotoId) } } });
assert(gallery.data.previewItems.every(p => !p.collectionPhotoId), 'legacy preview must not swipe into thumbnails');
require('../miniprogram/contributions/gallery/index');
const full = instantiate();
full.onLoad({ group: 'nature', photo: 'reservoir' });
assert.strictEqual(full.data.photos[0].id, 'reservoir');
assert.strictEqual(full.data.photos.length, 6);
full.onPreview({ currentTarget: { dataset: { id: 'reservoir' } } });
assert.strictEqual(full.data.showPreview, true);
assert.strictEqual(full.data.photos[full.data.previewIndex].src, '/contributions/images/reservoir.jpg');
assert(full.data.photos.every(photo => photo.src.startsWith('/contributions/images/')));
full.onPreviewChange({ detail: { current: 1 } });
assert.strictEqual(full.data.previewIndex, 1);
full.onClosePreview();
assert.strictEqual(full.data.showPreview, false);
full.selectGroup('invalid');
assert.strictEqual(full.data.photos.length, 13);
require('../miniprogram/pages/site-detail/index');
const site = instantiate();
site.onLoad({ id: 'site_5' });
assert.strictEqual(site.data.photoCollection.count, 2);
assert.strictEqual(site.data.canNavigate, false);
site.onGoToGallery();
assert.strictEqual(navigated, '/contributions/gallery/index?group=qiaolin_branch');
site.onLoad({ id: 'landmark_1' });
assert.strictEqual(site.data.photoCollection.count, 3);
site.onLoad({ id: 'site_6' });
assert.strictEqual(site.data.photoCollection, null);
console.log('contributedPhotos.test.js: 13 photo checksums, gallery routing, full previews and truthful site bindings passed');
