'use strict';
const assert = require('assert');
const geo = require('../miniprogram/utils/geo.js');
assert.strictEqual(geo.distanceKm(0, 0, 0, 0), 0);
assert(Math.abs(geo.distanceKm(0, 0, 0, 1) - 111.195) < 0.01);
assert(Number.isFinite(geo.distanceKm(90, 0, -90, 180)));
for (const coords of [[91, 0, 0, 0], [0, 181, 0, 0], [NaN, 0, 0, 0]]) {
  assert.strictEqual(geo.distanceKm(...coords), null);
}
assert.strictEqual(geo.formatDistance(0), '0米');
assert.strictEqual(geo.estimateMinutes(0, 4.5), 0);
assert.strictEqual(geo.estimateMinutes(4.5, 4.5), 60);
assert.strictEqual(geo.estimateMinutes(-1, 30), null);
assert.strictEqual(geo.formatDistance(-1), '待定位');
let definition;
let request;
global.Page = value => { definition = value; };
global.wx = { getLocation(options) { request = options; }, showToast() {} };
require('../miniprogram/pages/village-detail/index.js');
const page = { ...definition, data: { ...definition.data, village: { latitude: 26.620306, longitude: 114.046347 } }, setData(value) { Object.assign(this.data, value); } };
page.onLocateMe();
assert.strictEqual(request.type, 'gcj02');
request.success({ latitude: 26.620306, longitude: 114.046347 });
assert.strictEqual(page.data.distanceText, '0米');
assert.strictEqual(page.data.walkTimeText, '约0分钟');
assert(page.data.locationMessage.includes('直线距离') && page.data.locationMessage.includes('非实际路线'));
page.onLocateMe();
assert.strictEqual(page.data.distanceText, '待定位', 'new request clears previous result');
request.fail({ errMsg: 'getLocation:fail auth deny' });
assert.strictEqual(page.data.locating, false);
assert(page.data.locationMessage.includes('权限'));
assert.strictEqual(page.data.walkTimeText, '待定位');
page.onLocateMe();
request.fail({ errMsg: 'getLocation:fail timeout' });
assert(page.data.locationMessage.includes('系统定位'), 'timeout must not be reported as permission denial');
page.onLocateMe();
request.success({ latitude: 999, longitude: 114 });
assert.strictEqual(page.data.distanceText, '待定位');
assert(page.data.locationMessage.includes('有效坐标'));
console.log('locationEstimate.test.js: distances, travel estimates, invalid coordinates and location failure recovery passed');
